import { Project } from "./types";

export const PROJECTS: Project[] = [
    {
        id: "neon-dreams",
        title: "Boteco Tijuca",
        category: "Vídeo",
        description: "Uma experiência cinematográfica cyberpunk.",
        client: "SynthWave Records",
        year: "2024",
        thumbnail: "/videos/p1.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p1.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["DaVinci Resolve", "Photoshop"],
    },
    {
        id: "horizon-tech",
        title: "Horizon Tech",
        category: "Vídeo",
        description: "Comercial de lançamento de produto.",
        client: "Horizon Corp",
        year: "2023",
        thumbnail: "/videos/p2.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p2.mp4",
                type: "image",
                orientation: "vertical",
            },
        ],
        tools: ["After Effects", "Cinema 4D", "Illustrator"],
    },
    {
        id: "horizon-tech",
        title: "Horizon Tech",
        category: "Vídeo",
        description: "Comercial de lançamento de produto.",
        client: "Horizon Corp",
        year: "2023",
        thumbnail: "/videos/p3.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p3.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["After Effects", "Cinema 4D", "Illustrator"],
    },
    {
        id: "urban-pulse",
        title: "Urban Pulse",
        category: "Vídeo",
        description: "Documentário estilo cultura de rua.",
        client: "Vogue Japan (Mock)",
        year: "2023",
        thumbnail: "/videos/p4.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p4.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["Premiere Pro", "Lightroom"],
    },
    {
        id: "urban-pulse",
        title: "Urban Pulse",
        category: "Vídeo",
        description: "Documentário estilo cultura de rua.",
        client: "Vogue Japan (Mock)",
        year: "2023",
        thumbnail: "/videos/p5.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p5.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["Premiere Pro", "Lightroom"],
    },
    {
        id: "web-portfolio",
        title: "Creative Folio",
        category: "Site",
        description: "Website interativo 3D.",
        client: "Pessoal",
        year: "2024",
        thumbnail: "/videos/p6.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p6.mp4",
                type: "image",
                orientation: "vertical",
            },
        ],
        tools: ["React", "Three.js", "Tailwind"],
    },
    {
        id: "fashion-edit",
        title: "Summer Vibes",
        category: "Vídeo",
        description: "Edição dinâmica para marca de roupas.",
        client: "Local Brand",
        year: "2024",
        thumbnail: "/videos/p7.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p7.mp4",
                type: "image",
                orientation: "vertical",
            },
        ],
        tools: ["Premiere Pro", "After Effects"],
    },
    {
        id: "corp-Vídeo",
        title: "Identity System",
        category: "Vídeo",
        description: "Identidade visual corporativa.",
        client: "FinStart",
        year: "2023",
        thumbnail: "/videos/p8.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p8.mp4",
                type: "image",
                orientation: "vertical",
            },
        ],
        tools: ["Figma", "Illustrator"],
    },
    {
        id: "tech-innovation",
        title: "Tech Innovation",
        category: "Vídeo",
        description: "Projeto de inovação tecnológica.",
        client: "Tech Corp",
        year: "2024",
        thumbnail: "/videos/p9.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p9.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["DaVinci Resolve", "Photoshop"],
    },
    {
        id: "creative-vision",
        title: "Creative Vision",
        category: "Vídeo",
        description: "Exploração criativa de conceitos visuais.",
        client: "Studio Creative",
        year: "2024",
        thumbnail: "/videos/p10.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p10.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["Premiere Pro", "DaVinci Resolve"],
    },
    {
        id: "brand-storytelling",
        title: "Brand Storytelling",
        category: "Vídeo",
        description: "Narrativa visual para marca de lifestyle.",
        client: "Lifestyle Brand",
        year: "2024",
        thumbnail: "/videos/p11.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p11.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["DaVinci Resolve", "Photoshop"],
    },
    {
        id: "motion-Vídeo",
        title: "Motion Vídeo",
        category: "Vídeo",
        description: "Animações de movimento para web.",
        client: "Digital Agency",
        year: "2024",
        thumbnail: "/videos/p12.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p12.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["After Effects", "Cinema 4D"],
    },
    {
        id: "visual-effects",
        title: "Visual Effects",
        category: "Vídeo",
        description: "Efeitos visuais para comercial.",
        client: "Production House",
        year: "2024",
        thumbnail: "/videos/p13.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p13.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["After Effects", "Cinema 4D"],
    },
    {
        id: "music-video",
        title: "Music Video",
        category: "Vídeo",
        description: "Videoclipe para artista independente.",
        client: "Independent Artist",
        year: "2024",
        thumbnail: "/videos/p14.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p14.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["Premiere Pro", "DaVinci Resolve"],
    },
    {
        id: "corporate-video",
        title: "Corporate Video",
        category: "Vídeo",
        description: "Vídeo corporativo para empresa.",
        client: "Corporate Company",
        year: "2024",
        thumbnail: "/videos/p15.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p15.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["DaVinci Resolve", "Photoshop"],
    },
    {
        id: "commercial-spot",
        title: "Commercial Spot",
        category: "Vídeo",
        description: "Spot publicitário para TV.",
        client: "Advertising Agency",
        year: "2024",
        thumbnail: "/videos/p16.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p16.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["Premiere Pro", "After Effects"],
    },
    {
        id: "event-coverage",
        title: "Event Coverage",
        category: "Vídeo",
        description: "Cobertura de evento ao vivo.",
        client: "Event Manager",
        year: "2024",
        thumbnail: "/videos/p17.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p17.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["DaVinci Resolve", "Photoshop"],
    },
    {
        id: "product-launch",
        title: "Product Launch",
        category: "Vídeo",
        description: "Lançamento de novo produto.",
        client: "E-commerce Brand",
        year: "2024",
        thumbnail: "/videos/p18.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p18.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["Premiere Pro", "After Effects"],
    },
    {
        id: "documentary",
        title: "Documentary",
        category: "Vídeo",
        description: "Documentário sobre tema social.",
        client: "Production Company",
        year: "2024",
        thumbnail: "/videos/p19.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p19.mp4",
                type: "video",
                orientation: "horizontal",
            },
        ],
        tools: ["Premiere Pro", "DaVinci Resolve"],
    },
    {
        id: "travel-vlog",
        title: "Travel Vlog",
        category: "Vídeo",
        description: "Vídeo de viagem e exploração.",
        client: "Travel Influencer",
        year: "2024",
        thumbnail: "/videos/p20.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p20.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["DaVinci Resolve", "Photoshop"],
    },
    {
        id: "gaming-highlight",
        title: "Gaming Highlight",
        category: "Vídeo",
        description: "Destaque de gameplay e competição.",
        client: "Esports Team",
        year: "2024",
        thumbnail: "/videos/p21.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p21.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["Premiere Pro", "After Effects"],
    },
    {
        id: "animation-sequence",
        title: "Animation Sequence",
        category: "Vídeo",
        description: "Sequência de animação 3D.",
        client: "Animation Studio",
        year: "2024",
        thumbnail: "/videos/p22.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p22.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["Cinema 4D", "After Effects"],
    },
    {
        id: "podcast-intro",
        title: "Podcast Intro",
        category: "Vídeo",
        description: "Introdução dinâmica para podcast.",
        client: "Podcast Network",
        year: "2024",
        thumbnail: "/videos/p23.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p23.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["After Effects", "Premiere Pro"],
    },
    {
        id: "social-media",
        title: "Social Media Content",
        category: "Vídeo",
        description: "Conteúdo otimizado para redes sociais.",
        client: "Social Brand",
        year: "2024",
        thumbnail: "/videos/p24.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p24.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["DaVinci Resolve", "Photoshop"],
    },
    {
        id: "workout-video",
        title: "Workout Video",
        category: "Vídeo",
        description: "Série de exercícios e fitness.",
        client: "Fitness Coach",
        year: "2024",
        thumbnail: "/videos/p25.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/p25.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["Premiere Pro", "Lightroom"],
    },
    {
        id: "cooking-show",
        title: "Cooking Show",
        category: "Vídeo",
        description: "Episódio de programa culinário.",
        client: "Culinary Channel",
        year: "2024",
        thumbnail: "/videos/p26.mp4",
        thumbnailOrientation: "horizontal",
        media: [
            {
                url: "/videos/p26.mp4",
                type: "video",
                orientation: "horizontal",
            },
        ],
        tools: ["Premiere Pro", "DaVinci Resolve"],
    },
    {
        id: "esquenta-special",
        title: "Esquenta Special",
        category: "Vídeo",
        description: "Conteúdo especial e exclusivo.",
        client: "Content Creator",
        year: "2024",
        thumbnail: "/videos/Esquenta.mp4",
        thumbnailOrientation: "vertical",
        media: [
            {
                url: "/videos/Esquenta.mp4",
                type: "video",
                orientation: "vertical",
            },
        ],
        tools: ["DaVinci Resolve", "Photoshop"],
    },
];
